platform :ios, '17.0'

use_frameworks!

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

def shared_pods
  # swiftlint; https://github.com/realm/SwiftLint
  pod 'SwiftLint', '0.41', :inhibit_warnings => true
  
  # Network sniffer; MUST BE CONFIGURED ONLY FOR DEBUG; https://github.com/kasketis/netfox
  pod 'netfox', '1.21.0', :inhibit_warnings => true

  # Kingfisher; https://github.com/onevcat/Kingfisher
  pod 'Kingfisher', '7.10.1', :inhibit_warnings => true
end

target 'NetflixClone' do
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end
